version: '3.8'

services:
  redis:
    image: redis:8-alpine
    container_name: redisDesafio
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  app:
    build: .
    container_name: rateLimiterApp
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
